#' Explore graph scale based on the variable type
#'
#' This function provides a set of ggplot2 x-axis scales based on the variable type,
#' simplifying the process of creating axis scales for different types of data.
#'
#' @param var <`character`> The variable with its type as a class, either "pct",
#' "dollar" or "ind", or any other type for the default scale.
#' @param x_y <`character`> x or y axis?
#' @param ... Additional arguments passed to specific methods.
#'
#' @return A list containing ggplot2 x and y-axis scale functions.
#' @export
explore_graph_scale <- function(var, x_y, ...) {
  stopifnot(x_y %in% c("x", "y"))
  UseMethod("explore_graph_scale", var)
}

#' @describeIn explore_graph_scale The method for percentage values. Applies a
#' percentage scale to the x-axis.
#' @export
explore_graph_scale.pct <- function(var, x_y, ...) {
  scale <- sprintf("ggplot2::scale_%s_continuous", x_y)
  list(do.call(eval(parse(text = scale)), list(labels = scales::percent)))
}

#' @describeIn explore_graph_scale The method for dollar values. Applies a
#' dollar scale to the x-axis with appropriate suffixes based on the magnitude
#' of the data.
#' @param data_vals A numeric vector containing data values, required only for the
#' "dollar" method.
#' @export
explore_graph_scale.dollar <- function(var, x_y, data_vals, ...) {

  # Get the minimum number of significant digit
  min_dig <- min_sig_digits(data_vals)

  # Denpending on the magnitude of the number, compact differently
  scl <- if (min_dig >= 10) {
    scales::label_dollar(scale = 1 / 1e+09, suffix = "B")
  } else if (min_dig >= 7) {
    scales::label_dollar(scale = 1 / 1e+06, suffix = "M")
  } else if (min_dig >= 4) {
    scales::label_dollar(scale = 1 / 1e+03, suffix = "K")
  } else {
    scales::label_dollar()
  }

  # Return the ggplot2 scale
  scale <- sprintf("ggplot2::scale_%s_continuous", x_y)
  list(do.call(eval(parse(text = scale)), list(labels = scl)))
}

#' @describeIn explore_graph_scale The method for ordinal values.
#' @param lang <`character` Which language should the label be translated to.
#' Defaults to NULL for no translation.
#' @param df <`character`> The combination of the region under study and the
#' scale at which the user is on, e.g. `CMA_CSD`. The output of
#' \code{\link{update_df}}.
#' @param data_vals A numeric vector containing data values, required only for the
#' "dollar" method.
#' @export
explore_graph_scale.ind <- function(var, x_y, df, data_vals, lang = NULL, ...) {
  explore_graph_scale_ind(var = var, x_y = x_y, df = df,
                          data_vals = data_vals, lang = lang, ...)
}

#' @describeIn explore_graph_scale The default method for unspecified variable
#' types. Applies a comma scale to the x-axis.
#' @export
explore_graph_scale.default <- function(var, x_y, ...) {
  scale <- sprintf("ggplot2::scale_%s_continuous", x_y)
  list(do.call(eval(parse(text = scale)), list(labels = scales::comma)))
}

#' Explore Graph Scale Indice
#'
#' This function generates a scale for a ggplot2 graph based on the variable \code{var}
#' and the coordinate axis specified in \code{x_y}. The function dispatches to
#' specialized methods based on the type of \code{var}, either scalar or ordinal.
#'
#' @param var <`character`> The variable with its type as a class, either "scale",
#' "ordinal".
#' @param x_y <`character`> x or y axis?
#' @param lang <`character` Which language should the label be translated to.
#' Defaults to NULL for no translation.
#' @param df <`character`> The combination of the region under study and the
#' scale at which the user is on, e.g. `CMA_CSD`. The output of
#' \code{\link{update_df}}.
#' @param ... Additional arguments passed to the underlying ggplot2 functions.
#'
#' @return A list containing the ggplot2 scale object generated by the specialized
#' method.
explore_graph_scale_ind <- function(var, x_y, df, lang = NULL, ...) {
  UseMethod("explore_graph_scale_ind", var)
}

#' @describeIn explore_graph_scale_ind scalar method for index values
#' @param data_vals <`numeric vector`> containing data values
#' @export
explore_graph_scale_ind.scalar <- function(var, x_y, df, lang = NULL, data_vals, ...) {

  # Grab the min and max breaks and switch them to numeric. TKTK NOT ON `IND`
  # outliers <- find_outliers(data_vals)
  # if (length(outliers) > 0) data_vals <- data_vals[-outliers]
  breaks <- c(min(data_vals, na.rm = TRUE), max(data_vals, na.rm = TRUE))

  # Get the labels, same as the legends
  labels <- legend_breaks.q5_ind(var, df = df, lang = lang)
  labels <- labels[!sapply(labels, is.null)]
  labels <- unlist(labels)

  # Make the the length of breaks is the same as the one of the labels
  breaks <- seq(from = breaks[1], to = breaks[2], length.out = length(labels))
  names(labels) <- breaks

  # Return the scale as a list
  scale <- sprintf("ggplot2::scale_%s_continuous", x_y)
  list(do.call(eval(parse(text = scale)), list(labels = labels,
                                               breaks = breaks)))
}

#' @describeIn explore_graph_scale_ind ordinal method for index values
#' @export
explore_graph_scale_ind.ordinal <- function(var, x_y, df, lang = NULL, ...) {
  breaks <- var_get_breaks(var, df = df)
  labels <-  c(NA_character_, legend_breaks.q5_ind(var, df = df, lang = lang))
  names(labels) <- as.character(breaks)

  scale <- sprintf("ggplot2::scale_%s_discrete", x_y)
  list(do.call(eval(parse(text = scale)), list(labels = labels,
                                               breaks = breaks)))
}
